### ISSUE TITLE
Pull conda-build 3.18.x ?

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-build-feedstock#106]
conda-build 3.18.x is clearly not ready yet, as we've had to pull out all the versions we've had. Even 3.18.8 is not ready yet where `run_exports` differ based on package build number.

xref: https://github.com/conda/conda-build/issues/3583#issuecomment-510856158

cc @conda-forge/core

**Comment by msarahan** [comment]
Pulling it is fine, but you need to note exactly what behaviors are blocking, otherwise we won't know when it's OK to use again.

**Comment by isuruf** [comment]
edited description with https://github.com/conda/conda-build/issues/3583#issuecomment-510856158

**Comment by jjhelmus** [comment]
I opened conda/conda-build#3617 for this particular issue.

**Comment by isuruf** [comment]
Or we can add https://github.com/conda/conda-build/pull/3603 as a patch here

**Comment by mbargull** [comment]
Quoting myself from https://github.com/conda/conda-build/issues/3617#issuecomment-513956963:
> But if it's inconsistent with the source data, we really shouldn't use it until it is.
> 
> Meaning, if gh-3603 restores correctness, then please merge that PR.

So, if current behavior is incorrect and with https://github.com/conda/conda-build/pull/3603 applied it is correct again, then I think patching it for conda-forge is a viable option.

**Comment by jjhelmus** [comment]
conda/conda-build#3621 fixes the issue but allow opt-in use of channeldata via a command line flag.  I'll tag and release a new version of conda-build tomorrow with that change.

**Comment by dhirschfeld** [comment]
> *I'll tag and release a new version of conda-build tomorrow with that change*

That's great - I see it as pretty important to get a non-broken `conda-build` out there.

I honestly think the `--use-channeldata` argument should currently raise an exception as, until the `channeldata.json` is fixed, it's  functionally equivalent to `--silently-create-broken-package`

**Comment by jjhelmus** [comment]
conda-build 3.18.9 PR, #107

**Comment by msarahan** [comment]
If it really matters to you, @dhirschfeld, then perhaps you might consider spending more time doing something about it?  @jjhelmus has altered the default to no longer be broken.  Perhaps you could be happy with that and spare us your arm-chair coding and sarcasm?  Please channel your frustration into more positive outlets.

**Comment by dhirschfeld** [comment]
There was no sarcasm or offence intended there so I apologise if I did cause any offence.

That said, it's a fact that because the `channeldata.json` file doesn't include the correct `run_exports` using it will lead to broken environments. I think it's a bit dangerous to make available an option which doesn't currently work and so I voiced my opinion.

No one else at my company will know that `--use-channeldata` doesn't currently work correctly so they may try it out to get some performance improvements. If they then publish a package it'll be me running around pulling it from our internal repos.

It really does matter to me that less experienced developers can use `conda` with confidence that it will do the right thing or at the very least fail loudly. Silently doing the wrong thing is the worst type of bug for my/your users.

As I mentioned, I'm otherwise happy that @jjhelmus's PR fixes the problem due to the default of False and I'm keen to deploy a version including that fix ASAP.

I honestly think `conda-build` would be better (more robust/stable) if `--use-channeldata=True` raised an exception until the format was fixed but I don't see that as my call to make. Nevertheless I think providing feedback is valuable for the maintainers. As such I open numerous issues, each of which highlights a problem that I or my users have encountered in practice. I do also provide PRs where the fix is simple and obvious and doesn't require fundamental design decisions which I think are the remit of the maintainers to decide how to solve.
